package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Caracteristique generated by hbm2java
 */
@Entity
@Table(name="caracteristique"
    ,schema="public"
)
public class Caracteristique  implements java.io.Serializable {


     private int idcaracteristique;
     private Produit produit;
     private String dimension;
     private String image;
     private String nomcaract;
     private String particularite;

    public Caracteristique() {
    }

	
    public Caracteristique(int idcaracteristique) {
        this.idcaracteristique = idcaracteristique;
    }
    public Caracteristique(int idcaracteristique, Produit produit, String dimension, String image, String nomcaract, String particularite) {
       this.idcaracteristique = idcaracteristique;
       this.produit = produit;
       this.dimension = dimension;
       this.image = image;
       this.nomcaract = nomcaract;
       this.particularite = particularite;
    }
   
     @Id 
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @NotNull
    @Column(name="idcaracteristique")
    public int getIdcaracteristique() {
        return this.idcaracteristique;
    }
    
    public void setIdcaracteristique(int idcaracteristique) {
        this.idcaracteristique = idcaracteristique;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproduit")
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    
    @Column(name="dimension", length=254)
    public String getDimension() {
        return this.dimension;
    }
    
    public void setDimension(String dimension) {
        this.dimension = dimension;
    }

    
    @Column(name="image", length=254)
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }

    
    @Column(name="nomcaract", length=254)
    public String getNomcaract() {
        return this.nomcaract;
    }
    
    public void setNomcaract(String nomcaract) {
        this.nomcaract = nomcaract;
    }

    
    @Column(name="particularite", length=254)
    public String getParticularite() {
        return this.particularite;
    }
    
    public void setParticularite(String particularite) {
        this.particularite = particularite;
    }




}


