package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChefServiceOuvrier generated by hbm2java
 */
@Entity
@Table(name="chef_service_ouvrier"
    ,schema="public"
)
public class ChefServiceOuvrier  implements java.io.Serializable {


     private ChefServiceOuvrierId id;
     private Chefservice chefservice;
     private Ouvrier ouvrier;

    public ChefServiceOuvrier() {
    }

    public ChefServiceOuvrier(ChefServiceOuvrierId id, Chefservice chefservice, Ouvrier ouvrier) {
       this.id = id;
       this.chefservice = chefservice;
       this.ouvrier = ouvrier;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idchefservice", column=@Column(name="idchefservice", nullable=false) ), 
        @AttributeOverride(name="idouvrier", column=@Column(name="idouvrier", nullable=false) ) } )
    public ChefServiceOuvrierId getId() {
        return this.id;
    }
    
    public void setId(ChefServiceOuvrierId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idchefservice", nullable=false, insertable=false, updatable=false)
    public Chefservice getChefservice() {
        return this.chefservice;
    }
    
    public void setChefservice(Chefservice chefservice) {
        this.chefservice = chefservice;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idouvrier", nullable=false, insertable=false, updatable=false)
    public Ouvrier getOuvrier() {
        return this.ouvrier;
    }
    
    public void setOuvrier(Ouvrier ouvrier) {
        this.ouvrier = ouvrier;
    }




}


