package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChefServiceOuvrierId generated by hbm2java
 */
@Embeddable
public class ChefServiceOuvrierId  implements java.io.Serializable {


     private int idchefservice;
     private int idouvrier;

    public ChefServiceOuvrierId() {
    }

    public ChefServiceOuvrierId(int idchefservice, int idouvrier) {
       this.idchefservice = idchefservice;
       this.idouvrier = idouvrier;
    }
   


    @Column(name="idchefservice", nullable=false)
    public int getIdchefservice() {
        return this.idchefservice;
    }
    
    public void setIdchefservice(int idchefservice) {
        this.idchefservice = idchefservice;
    }


    @Column(name="idouvrier", nullable=false)
    public int getIdouvrier() {
        return this.idouvrier;
    }
    
    public void setIdouvrier(int idouvrier) {
        this.idouvrier = idouvrier;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChefServiceOuvrierId) ) return false;
		 ChefServiceOuvrierId castOther = ( ChefServiceOuvrierId ) other; 
         
		 return (this.getIdchefservice()==castOther.getIdchefservice())
 && (this.getIdouvrier()==castOther.getIdouvrier());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdchefservice();
         result = 37 * result + this.getIdouvrier();
         return result;
   }   


}


