package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ClientCommandeId generated by hbm2java
 */
@Embeddable
public class ClientCommandeId  implements java.io.Serializable {


     private int idclient;
     private int idcommande;

    public ClientCommandeId() {
    }

    public ClientCommandeId(int idclient, int idcommande) {
       this.idclient = idclient;
       this.idcommande = idcommande;
    }
   


    @Column(name="idclient", nullable=false)
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }


    @Column(name="idcommande", nullable=false)
    public int getIdcommande() {
        return this.idcommande;
    }
    
    public void setIdcommande(int idcommande) {
        this.idcommande = idcommande;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ClientCommandeId) ) return false;
		 ClientCommandeId castOther = ( ClientCommandeId ) other; 
         
		 return (this.getIdclient()==castOther.getIdclient())
 && (this.getIdcommande()==castOther.getIdcommande());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdclient();
         result = 37 * result + this.getIdcommande();
         return result;
   }   


}


