package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Objects;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name="client"
    ,schema="public"
)
public class Client  implements java.io.Serializable {


     private int idclient;
    
     private String adressemail;
     private String lieuderesidence;
     private String nomclient;
     private String prenomclient;
     private String sexe;
     private String telephone;
     private Set<ClientCommande> clientCommandes = new HashSet<ClientCommande>(0);

    public Client() {
    }

	
    public Client(int idclient) {
        this.idclient = idclient;
    }
    public Client(int idclient, String adressemail, String lieuderesidence, String nomclient, String prenomclient, String sexe, String telephone, Set<ClientCommande> clientCommandes) {
       this.idclient = idclient;
       
       this.adressemail = adressemail;
       this.lieuderesidence = lieuderesidence;
       this.nomclient = nomclient;
       this.prenomclient = prenomclient;
       this.sexe = sexe;
       this.telephone = telephone;
       this.clientCommandes = clientCommandes;
    }
   
    @Id 
    @NotNull
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idclient")
    public int getIdclient() {
        return this.idclient;
    }
    
    public void setIdclient(int idclient) {
        this.idclient = idclient;
    }


  
    
    @Column(name="adressemail", unique = true, length=254)
    public String getAdressemail() {
        return this.adressemail;
    }
    
    public void setAdressemail(String adressemail) {
        this.adressemail = adressemail;
    }

    
    @Column(name="lieuderesidence", length=254)
    public String getLieuderesidence() {
        return this.lieuderesidence;
    }
    
    public void setLieuderesidence(String lieuderesidence) {
        this.lieuderesidence = lieuderesidence;
    }

    
    @Column(name="nomclient", length=254)
    public String getNomclient() {
        return this.nomclient;
    }
    
    public void setNomclient(String nomclient) {
        this.nomclient = nomclient;
    }

    
    @Column(name="prenomclient", length=254)
    public String getPrenomclient() {
        return this.prenomclient;
    }
    
    public void setPrenomclient(String prenomclient) {
        this.prenomclient = prenomclient;
    }

    
    @Column(name="sexe", length=254)
    public String getSexe() {
        return this.sexe;
    }
    
    public void setSexe(String sexe) {
        this.sexe = sexe;
    }

    
    @Column(name="telephone",unique = true , length=254)
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="client")
    public Set<ClientCommande> getClientCommandes() {
        return this.clientCommandes;
    }
    
    public void setClientCommandes(Set<ClientCommande> clientCommandes) {
        this.clientCommandes = clientCommandes;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + this.idclient;
        hash = 59 * hash + Objects.hashCode(this.adressemail);
        hash = 59 * hash + Objects.hashCode(this.lieuderesidence);
        hash = 59 * hash + Objects.hashCode(this.nomclient);
        hash = 59 * hash + Objects.hashCode(this.prenomclient);
        hash = 59 * hash + Objects.hashCode(this.sexe);
        hash = 59 * hash + Objects.hashCode(this.telephone);
        hash = 59 * hash + Objects.hashCode(this.clientCommandes);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Client other = (Client) obj;
        if (this.idclient != other.idclient) {
            return false;
        }
        if (!Objects.equals(this.adressemail, other.adressemail)) {
            return false;
        }
        if (!Objects.equals(this.lieuderesidence, other.lieuderesidence)) {
            return false;
        }
        if (!Objects.equals(this.nomclient, other.nomclient)) {
            return false;
        }
        if (!Objects.equals(this.prenomclient, other.prenomclient)) {
            return false;
        }
        if (!Objects.equals(this.sexe, other.sexe)) {
            return false;
        }
        if (!Objects.equals(this.telephone, other.telephone)) {
            return false;
        }
        if (!Objects.equals(this.clientCommandes, other.clientCommandes)) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "Client{" + "idclient=" + idclient + ", adressemail=" + adressemail + ", lieuderesidence=" + lieuderesidence + ", nomclient=" + nomclient + ", prenomclient=" + prenomclient + ", sexe=" + sexe + ", telephone=" + telephone + ", clientCommandes=" + clientCommandes + '}';
    }




}


