package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeproduitId generated by hbm2java
 */
@Embeddable
public class CommandeproduitId  implements java.io.Serializable {


     private int idcommande;
     private int idproduit;

    public CommandeproduitId() {
    }

    public CommandeproduitId(int idcommande, int idproduit) {
       this.idcommande = idcommande;
       this.idproduit = idproduit;
    }
   


    @Column(name="idcommande", nullable=false)
    public int getIdcommande() {
        return this.idcommande;
    }
    
    public void setIdcommande(int idcommande) {
        this.idcommande = idcommande;
    }


    @Column(name="idproduit", nullable=false)
    public int getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(int idproduit) {
        this.idproduit = idproduit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CommandeproduitId) ) return false;
		 CommandeproduitId castOther = ( CommandeproduitId ) other; 
         
		 return (this.getIdcommande()==castOther.getIdcommande())
 && (this.getIdproduit()==castOther.getIdproduit());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdcommande();
         result = 37 * result + this.getIdproduit();
         return result;
   }   


}


