package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name="commande"
    ,schema="public"
)
public class Commande  implements java.io.Serializable {


     private int idcommande;
     private Secretaire secretaire;
     private Date datecommande;
     private Date datelivraison;
     private Set<ClientCommande> clientCommandes = new HashSet<ClientCommande>(0);
     private Set<Commandeproduit> commandeproduits = new HashSet<Commandeproduit>(0);

    public Commande() {
    }

	
    public Commande(int idcommande) {
        this.idcommande = idcommande;
    }
    public Commande(int idcommande, Secretaire secretaire, Date datecommande, Date datelivraison, Set<ClientCommande> clientCommandes, Set<Commandeproduit> commandeproduits) {
       this.idcommande = idcommande;
       this.secretaire = secretaire;
       this.datecommande = datecommande;
       this.datelivraison = datelivraison;
       this.clientCommandes = clientCommandes;
       this.commandeproduits = commandeproduits;
    }
   
    @Id 
    @NotNull
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name="idcommande")
    public int getIdcommande() {
        return this.idcommande;
    }
    
    public void setIdcommande(int idcommande) {
        this.idcommande = idcommande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="secretaire_id")
    public Secretaire getSecretaire() {
        return this.secretaire;
    }
    
    public void setSecretaire(Secretaire secretaire) {
        this.secretaire = secretaire;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datecommande", length=29)
    public Date getDatecommande() {
        return this.datecommande;
    }
    
    public void setDatecommande(Date datecommande) {
        this.datecommande = datecommande;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="datelivraison", length=29)
    public Date getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(Date datelivraison) {
        this.datelivraison = datelivraison;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commande")
    public Set<ClientCommande> getClientCommandes() {
        return this.clientCommandes;
    }
    
    public void setClientCommandes(Set<ClientCommande> clientCommandes) {
        this.clientCommandes = clientCommandes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="commande")
    public Set<Commandeproduit> getCommandeproduits() {
        return this.commandeproduits;
    }
    
    public void setCommandeproduits(Set<Commandeproduit> commandeproduits) {
        this.commandeproduits = commandeproduits;
    }




}


