package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commandeproduit generated by hbm2java
 */
@Entity
@Table(name="commandeproduit"
    ,schema="public"
)
public class Commandeproduit  implements java.io.Serializable {


     private CommandeproduitId id;
     private Commande commande;
     private Produit produit;
     private BigDecimal prixtotal;
     private Integer quantitecommande;

    public Commandeproduit() {
    }

	
    public Commandeproduit(CommandeproduitId id, Commande commande, Produit produit) {
        this.id = id;
        this.commande = commande;
        this.produit = produit;
    }
    public Commandeproduit(CommandeproduitId id, Commande commande, Produit produit, BigDecimal prixtotal, Integer quantitecommande) {
       this.id = id;
       this.commande = commande;
       this.produit = produit;
       this.prixtotal = prixtotal;
       this.quantitecommande = quantitecommande;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idcommande", column=@Column(name="idcommande", nullable=false) ), 
        @AttributeOverride(name="idproduit", column=@Column(name="idproduit", nullable=false) ) } )
    public CommandeproduitId getId() {
        return this.id;
    }
    
    public void setId(CommandeproduitId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idcommande", nullable=false, insertable=false, updatable=false)
    public Commande getCommande() {
        return this.commande;
    }
    
    public void setCommande(Commande commande) {
        this.commande = commande;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idproduit", nullable=false, insertable=false, updatable=false)
    public Produit getProduit() {
        return this.produit;
    }
    
    public void setProduit(Produit produit) {
        this.produit = produit;
    }

    
    @Column(name="prixtotal")
    public BigDecimal getPrixtotal() {
        return this.prixtotal;
    }
    
    public void setPrixtotal(BigDecimal prixtotal) {
        this.prixtotal = prixtotal;
    }

    
    @Column(name="quantitecommande")
    public Integer getQuantitecommande() {
        return this.quantitecommande;
    }
    
    public void setQuantitecommande(Integer quantitecommande) {
        this.quantitecommande = quantitecommande;
    }




}


