package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatierePremiereProduitId generated by hbm2java
 */
@Embeddable
public class MatierePremiereProduitId  implements java.io.Serializable {


     private int idproduit;
     private int idmatierepremiere;

    public MatierePremiereProduitId() {
    }

    public MatierePremiereProduitId(int idproduit, int idmatierepremiere) {
       this.idproduit = idproduit;
       this.idmatierepremiere = idmatierepremiere;
    }
   


    @Column(name="idproduit", nullable=false)
    public int getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(int idproduit) {
        this.idproduit = idproduit;
    }


    @Column(name="idmatierepremiere", nullable=false)
    public int getIdmatierepremiere() {
        return this.idmatierepremiere;
    }
    
    public void setIdmatierepremiere(int idmatierepremiere) {
        this.idmatierepremiere = idmatierepremiere;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatierePremiereProduitId) ) return false;
		 MatierePremiereProduitId castOther = ( MatierePremiereProduitId ) other; 
         
		 return (this.getIdproduit()==castOther.getIdproduit())
 && (this.getIdmatierepremiere()==castOther.getIdmatierepremiere());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdproduit();
         result = 37 * result + this.getIdmatierepremiere();
         return result;
   }   


}


