package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Matierepremiere generated by hbm2java
 */
@Entity
@Table(name="matierepremiere"
    ,schema="public"
)
public class Matierepremiere  implements java.io.Serializable {


     private int idmatierepremiere;
     private Dg dg;
     private Fournisseur fournisseur;
     private Integer datelivraison;
     private String description;
     private Integer nom;
     private Integer quantite;
     private Set<MatierePremiereProduit> matierePremiereProduits = new HashSet<MatierePremiereProduit>(0);

    public Matierepremiere() {
    }

	
    public Matierepremiere(int idmatierepremiere) {
        this.idmatierepremiere = idmatierepremiere;
    }
    public Matierepremiere(int idmatierepremiere, Dg dg, Fournisseur fournisseur, Integer datelivraison, String description, Integer nom, Integer quantite, Set<MatierePremiereProduit> matierePremiereProduits) {
       this.idmatierepremiere = idmatierepremiere;
       this.dg = dg;
       this.fournisseur = fournisseur;
       this.datelivraison = datelivraison;
       this.description = description;
       this.nom = nom;
       this.quantite = quantite;
       this.matierePremiereProduits = matierePremiereProduits;
    }
   
     @Id 

    
    @Column(name="idmatierepremiere", unique=true, nullable=false)
    public int getIdmatierepremiere() {
        return this.idmatierepremiere;
    }
    
    public void setIdmatierepremiere(int idmatierepremiere) {
        this.idmatierepremiere = idmatierepremiere;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="dg_id")
    public Dg getDg() {
        return this.dg;
    }
    
    public void setDg(Dg dg) {
        this.dg = dg;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idfournisseur")
    public Fournisseur getFournisseur() {
        return this.fournisseur;
    }
    
    public void setFournisseur(Fournisseur fournisseur) {
        this.fournisseur = fournisseur;
    }

    
    @Column(name="datelivraison")
    public Integer getDatelivraison() {
        return this.datelivraison;
    }
    
    public void setDatelivraison(Integer datelivraison) {
        this.datelivraison = datelivraison;
    }

    
    @Column(name="description", length=254)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="nom")
    public Integer getNom() {
        return this.nom;
    }
    
    public void setNom(Integer nom) {
        this.nom = nom;
    }

    
    @Column(name="quantite")
    public Integer getQuantite() {
        return this.quantite;
    }
    
    public void setQuantite(Integer quantite) {
        this.quantite = quantite;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="matierepremiere")
    public Set<MatierePremiereProduit> getMatierePremiereProduits() {
        return this.matierePremiereProduits;
    }
    
    public void setMatierePremiereProduits(Set<MatierePremiereProduit> matierePremiereProduits) {
        this.matierePremiereProduits = matierePremiereProduits;
    }




}


