package com.winmoney.entities;
// Generated 25 sept. 2018 22:38:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProduitServiceId generated by hbm2java
 */
@Embeddable
public class ProduitServiceId  implements java.io.Serializable {


     private int idservice;
     private int idproduit;

    public ProduitServiceId() {
    }

    public ProduitServiceId(int idservice, int idproduit) {
       this.idservice = idservice;
       this.idproduit = idproduit;
    }
   


    @Column(name="idservice", nullable=false)
    public int getIdservice() {
        return this.idservice;
    }
    
    public void setIdservice(int idservice) {
        this.idservice = idservice;
    }


    @Column(name="idproduit", nullable=false)
    public int getIdproduit() {
        return this.idproduit;
    }
    
    public void setIdproduit(int idproduit) {
        this.idproduit = idproduit;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProduitServiceId) ) return false;
		 ProduitServiceId castOther = ( ProduitServiceId ) other; 
         
		 return (this.getIdservice()==castOther.getIdservice())
 && (this.getIdproduit()==castOther.getIdproduit());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdservice();
         result = 37 * result + this.getIdproduit();
         return result;
   }   


}


